### ISSUE TITLE
Request to get a User access token

### ISSUE THREAD

**Issue by ineffablep** [bhushankumarl/eBay-node-client#12] opened 2018-11-26 20:40 UTC
Hi, 
How can I request Request to get a User access token to set it for eBay.catalog.createChangeRequest.

I have tried like this but not working

```
eBay.application.getOAuthToken({
        grant_type: 'authorization_code',
        scope: 'https://api.ebay.com/oauth/api_scope'
    }).then(token => {
    
});
```

**Comment by bhushankummar** [comment] 2018-11-28 18:18
What exactly error are you facing?

**Comment by bhushankummar** [comment] 2018-11-30 09:10
@ineffablep 
Documentation is available here.
https://developer.ebay.com/api-docs/static/oauth-tokens.html
Duplicate of #10

**Closed as completed by bhushankummar** 2018-11-30 09:10 UTC

**Comment by bhushankummar** [comment] 2018-12-14 13:40
@ineffablep 
#14 
Support has been extended in the same package. You can find the example here :
https://github.com/bhushankumarl/eBay-node-client/tree/master/examples/javaScript/user
